Check every property is set in the conversion methods
mphowardlab/lammpsio pull request #59
Opened 2024-09-30 15:55 UTC by clpetix

2024-09-30 16:00 UTC, clpetix commented
@mphoward this should address the issues that I had when using the GSD frame directly. The `to_hoomd_gsd` already checked all of the properties with `has_XX()`methods. 

Once this is good to go, then PR #54 should also be ready for review!

2024-10-01 13:17 UTC, mphoward requested changes
Overall this looks straightforward and makes sense! Please add a unit test that would fail before the change was applied and passes now. It could be as straightforward as passing an almost empty `Frame`

2024-10-01 13:17 UTC, mphoward commented on src/lammpsio/snapshot.py
>              warnings.warn("Some molecule IDs are negative, remapping needed.")
Move this inside the `if body is not None` check, it only needs to run if this field gets set

2024-10-01 13:17 UTC, mphoward commented on src/lammpsio/snapshot.py
> +            snap.position = frame.particles.position
Please add whitespace between these to improve readability
```suggestion
            snap.position = frame.particles.position

```

2024-10-01 14:37 UTC, clpetix commented
@mphoward I added a unit test that makes a snapshot from a minimal GSD and then checks that snap.molecule initializes to the default zeros when called. I also confirmed that this test previously failed before these changes. 

This should be good for you to look at again!

2024-10-01 15:36 UTC, mphoward requested changes
Thanks! I have one request to tweak the test and then this can be merged.

2024-10-01 15:58 UTC, clpetix commented
@mphoward , that makes sense. This should be good now!

2024-10-01 20:02 UTC, mphoward approved these changes
Thank you!

2024-10-01 20:02 UTC, merged